Parameter length overflow during opencl program build
arrayfire/arrayfire pull request #3032
Opened 2020-10-26 22:21 UTC by willyborn

Fixed: test 120 test_jit_opencl and 161 test_orb_opencl.
- test_jit generated an exception
- test_orb generated failure

Values for opencl parameter maximum length were hardcoded.  The maximum is now requested at the device, so that the correct value for all devices is used.

Description
-----------
* Fixes errors and crashes on iGPUs other than intel, which was also hardcoded.
* Noticed impact is a speed improvement of around 30% on opencl.
* The hardcoded values are now removed, so this is not tested for other devices.
* If desired, this can be backported since the change is very limited.

Changes to Users
----------------
* No changes, except on fixed bugs for some.

Checklist
---------
- [x] Rebased on latest master
- [x] Code compiles
- [x] Tests pass

2020-10-26 22:28 UTC, umar456 commented
This is interesting. I didn't know this parameter existed! I will test it on other devices and get back to you. Please, update the formatting of the code added and if possible please rebase your changes on top of master and removing the merge commit. 

Would also be nice if you could make the gitignore commit message more descriptive.

Thanks

2020-10-29 04:18 UTC, 9prady9 commented
> 
> 
> This is interesting. I didn't know this parameter existed! I will test it on other devices and get back to you. Please, update the formatting of the code added and if possible please rebase your changes on top of master and removing the merge commit.
> 
> Would also be nice if you could make the gitignore commit message more descriptive.
> 
> Thanks

Yes, for whatever reason, this isn't listed on online documentation of `clGetDeviceInfo`. However, it is present in the PDF specification sheets of versions 1.2, 2.2 and 3.0. So, it is not an extension or recent addition.

2020-10-29 04:21 UTC, 9prady9 reviewed
Looks good.

2020-10-29 04:21 UTC, 9prady9 commented on src/backend/opencl/Array.cpp
> +                                                                          : 6;
This and the earlier line as essentially identical as `device` returned

2020-11-02 09:31 UTC, 9prady9 requested changes
Looks good and works for NVIDIA and AMD(Kaveri APU) for all tests except one which failed on both devices.

Random number quality test is failing for both my GTX 1060 with CUDA 11.1 and AMD API Kaveri APU. Not sure if it is a problem from PR or master yet. @umar456 Can you please confirm if this is a known issue or new one.

One minor change, can you please remove the `isNvidia` and `isAmd` variables that aren't used anymore. They appear in warnings now, they are declared in the lines 303, 305.

Thank you.

2020-11-02 16:28 UTC, 9prady9 approved these changes

2020-11-02 16:35 UTC, umar456 approved these changes

2020-11-04 03:03 UTC, merged