The compare function should return false, for equal elements.
arrayfire/arrayfire pull request #3141
Opened 2021-06-01 20:53 UTC by willyborn

When compiling in debug mode, the MSVC compiler returns an non-compliance error.
The provided method should simulate the '<' function, not '<='.

Description
-----------
bug fix, could result in increase sort time or even incorrect results.

Changes to Users
----------------
None

Checklist
---------

- [x] Rebased on latest master
- [x] Code compiles
- [x] Tests pass
- [ ] Functions added to unified API
- [ ] Functions documented

2021-06-21 06:23 UTC, 9prady9 requested changes
I think this should also be changed https://github.com/arrayfire/arrayfire/blob/master/test/sift.cpp#L49

Can you also please change the following as well
https://github.com/arrayfire/arrayfire/blob/master/test/orb.cpp#L48
https://github.com/arrayfire/arrayfire/blob/master/test/orb.cpp#L48

2021-06-22 12:45 UTC, 9prady9 commented
@willyborn there is a merge commit in the PR commit history, please remove it.

2021-06-22 12:49 UTC, willyborn commented
I found an extra one in topk

2021-06-23 03:40 UTC, 9prady9 approved these changes

2021-06-23 03:41 UTC, merged