Rotate oneapi port
arrayfire/arrayfire pull request #3316
Opened 2022-10-23 18:04 UTC by pv-pterab-s

Description
-----------
These changes constitute a partially-functioning OneAPI port of the "rotate" function. Only supports nearest neighbor sampling. The tests (which only check nearest neighbor) pass except for the `char` input type. The `char` input type is yet to be supported by core arrayfire.

    ./test/rotate_oneapi --gtest_filter="-Rotate/6*"

Checklist
---------

- [X] Rebased on latest master
- [X] Code compiles
- [ ] Tests pass
- [ ] Functions added to unified API
- [ ] Functions documented

2022-11-08 03:06 UTC, syurkevi requested changes

2022-11-08 03:06 UTC, syurkevi commented on src/backend/oneapi/kernel/rotate.hpp
> +            const int yido = it.get_global_id(1);
revert to blockIdx_x based indexing. will investigate more after interp.hpp is integrated

2022-11-08 13:07 UTC, pv-pterab-s commented on src/backend/oneapi/rotate.cpp
> +        // case AF_INTERP_BILINEAR:
i'll try to get interp integrated, of course, but my opinion is that the interp abstraction adds too much complexity in the long run versus the value add on reuse. interp had to be dropped in order to make solid progress on debugging the `blockIdx_x based indexing` issue, above.

2023-01-07 18:47 UTC, closed without merging

2023-01-07 18:47 UTC, pv-pterab-s commented
dropping